//Armours
var armours = [
    {
        name: 'Nothing',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        weight: 0,
        excludes: [],
        type: 'normal',
        width:'120px',
        top:'60px',
        left:'-22px'
    },
    {
        name: 'INTERCEPTOR',
        hp: 860,
        heat: 265,
        cooling: 80,
        energy: 193,
        engRegen: 56,
        psyResist: 16,
        electricResist: 22,
        explosionResist: 22,
        weight: 309,
        excludes: [],
        type: 'normal',
        width:'120px',
        top:'36px',
        left:'-22px'
    },
    {
        name: 'ARCHIMOND_L',
        hp: 1090,
        heat: 265,
        cooling: 76,
        energy: 265,
        engRegen: 76,
        psyResist: 22,
        electricResist: 22,
        explosionResist: 22,
        weight: 363,
        excludes: [],
        type: 'normal',
        width:'120px',
        top:'6px',
        left:'-22px'
    },
    {
        name: 'AVENGER',
        hp: 1242,
        heat: 145,
        cooling: 48,
        energy: 193,
        engRegen: 64,
        psyResist: 16,
        electricResist: 22,
        explosionResist: 22,
        weight: 350,
        excludes: [],
        type: 'normal',
        width:'126px',
        top:'42px',
        left:'-22px'
    },
    {
        name: 'NIGHTMARE',
        hp: 879,
        heat: 290,
        cooling: 96,
        energy: 193,
        engRegen: 64,
        psyResist: 22,
        electricResist: 22,
        explosionResist: 16,
        weight: 315,
        excludes: [],
        type: 'normal',
        width:'120px',
        top:'36px',
        left:'-22px'
    },
    {
        name: 'BRUTALITY',
        hp: 1033,
        heat: 290,
        cooling: 88,
        energy: 217,
        engRegen: 64,
        psyResist: 22,
        electricResist: 22,
        explosionResist: 16,
        weight: 341,
        excludes: [],
        type: 'normal',
        width:'155px',
        top:'22px',
        left:'-56px'
    },
    {
        name: 'WINDIGO',
        hp: 982,
        heat: 301,
        cooling: 112,
        energy: 217,
        engRegen: 72,
        psyResist: 22,
        electricResist: 22,
        explosionResist: 16,
        weight: 345,
        excludes: [],
        type: 'normal',
        width:'165px',
        top:'36px',
        left:'-48px'
    },
    {
        name: 'ZARKARES',
        hp: 1136,
        heat: 312,
        cooling: 112,
        energy: 193,
        engRegen: 64,
        psyResist: 16,
        electricResist: 16,
        explosionResist: 24,
        weight: 362,
        excludes: [],
        type: 'normal',
        width:'135px',
        top:'36px',
        left:'-28px'
    },    
    {
        name: 'SABERTOOTH',
        hp: 1136,
        heat: 312,
        cooling: 112,
        energy: 193,
        engRegen: 64,
        psyResist: 16,
        electricResist: 16,
        explosionResist: 24,
        weight: 362,
        excludes: [],
        type: 'normal',
        width:'146px',
        top:'36px',
        left:'-44px'
    },
    {
        name: 'SITH',
        hp: 930,
        heat: 193,
        cooling: 64,
        energy: 245,
        engRegen: 112,
        psyResist: 22,
        electricResist: 16,
        explosionResist: 22,
        weight: 321,
        excludes: [],
        type: 'normal',
        width:'120px',
        top:'36px',
        left:'-22px'
    },
    {
        name: 'GRIMREAPER',
        hp: 879,
        heat: 193,
        cooling: 64,
        energy: 346,
        engRegen: 112,
        psyResist: 22,
        electricResist: 16,
        explosionResist: 22,
        weight: 329,
        excludes: [],
        type: 'normal',
        width:'125px',
        top:'26px',
        left:'-20px'
    },
    {
        name: 'NAGA',
        hp: 982,
        heat: 193,
        cooling: 72,
        energy: 279,
        engRegen: 104,
        psyResist: 22,
        electricResist: 16,
        explosionResist: 22,
        weight: 335,
        excludes: [],
        type: 'normal',
        width:'120px',
        top:'36px',
        left:'-13px'
    },
    {
        name: 'MOLTEN_PLATINUM_VEST',
        hp: 982,
        heat: 267,
        cooling: 96,
        energy: 193,
        engRegen: 64,
        psyResist: 44,
        electricResist: 22,
        explosionResist: 16,
        weight: 346,
        excludes: [],
        type: 'normal',
        width:'130px',
        top:'36px',
        left:'-22px'
    },
    {
        name: 'LIGHTNING_PLATINUM_VEST',
        hp: 982,
        heat: 193,
        cooling: 64,
        energy: 267,
        engRegen: 96,
        psyResist: 44,
        electricResist: 16,
        explosionResist: 22,
        weight: 346,
        excludes: [],
        type: 'normal',
        width:'130px',
        top:'36px',
        left:'-22px'
    },
    // fan
    {
        name: 'SPHINX',
        hp: 1090,
        heat: 224,
        cooling: 85,
        energy: 279,
        engRegen: 104,
        psyResist: 22,
        electricResist: 22,
        explosionResist: 22,
        weight: 366,
        excludes: [],
        type: 'normal',
        width:'120px',
        top:'18px',
        left:'-22px'
    },
    {
        name: 'SPHINIX',
        hp: 1000,
        heat: 330,
        cooling: 100,
        energy: 330,
        engRegen: 100,
        psyResist: 14,
        electricResist: 14,
        explosionResist: 14,
        weight: 340,
        excludes: [],
        type: 'normal',
        width:'120px',
        top:'20px',
        left:'-22px'
    },
    {
        name: 'BATTLE_ARMOUR',
        hp: 783,
        heat: 150,
        cooling: 150,
        energy: 150,
        engRegen: 150,
        psyResist: 22,
        electricResist: 14,
        explosionResist: 6,
        weight: 290,
        excludes: [],
        type: 'normal',
        width:'150px',
        top:'26px',
        left:'-45px'
    },
    {
        name: 'Storm',
        hp: 888,
        heat: 193,
        cooling: 93,
        energy: 265,
        engRegen: 125,
        psyResist: 22,
        electricResist: 14,
        explosionResist: 6,
        weight: 320,
        excludes: [],
        type: 'normal',
        width:'136px',
        top:'34px',
        left:'-24px'
    },
    {
        name: 'NAGA_EVO',
        hp: 1111,
        heat: 222,
        cooling: 75,
        energy: 300,
        engRegen: 90,
        psyResist: 16,
        electricResist: 16,
        explosionResist: 16,
        weight: 340,
        excludes: [],
        type: 'normal',
        width:'210px',
        top:'4px',
        left:'-58px'
    },
    {
        name: 'CONQUEROR',
        hp: 931,
        heat: 189,
        cooling: 93,
        energy: 79,
        engRegen: 52,
        psyResist: 14,
        electricResist: 14,
        explosionResist: 23,
        weight: 371,
        excludes: [],
        type: 'normal',
        width:'165px',
        top:'42px',
        left:'-40px'
    },
    {
        name: 'Matrix_torso',
        hp: 1000,
        heat: 211,
        cooling: 75,
        energy: 211,
        engRegen: 75,
        psyResist: 18,
        electricResist: 18,
        explosionResist: 18,
        weight: 355,
        excludes: [],
        type: 'normal',
        width:'118px',
        top:'39px',
        left:'-11px'
    },
    //test armours
    {
        name: 'ABADDON_TEST',
        hp: 870,
        heat: 350,
        cooling: 125,
        energy: 120,
        engRegen: 75,
        psyResist: 6,
        electricResist: 6,
        explosionResist: 12,
        weight: 345,
        excludes: [],
        type: 'normal',
        width:'114px',
        top:'39px',
        left:'-11px'
    },
    {
        name: 'ETHERION_TEST',
        hp: 870,
        heat: 120,
        cooling: 75,
        energy: 350,
        engRegen: 125,
        psyResist: 6,
        electricResist: 12,
        explosionResist: 6,
        weight: 345,
        excludes: [],
        type: 'normal',
        width:'118px',
        top:'30px',
        left:'-16px'
    },
    {
        name: 'COSMIC_TEST',
        hp: 2350,
        heat: 80,
        cooling: 40,
        energy: 80,
        engRegen: 40,
        psyResist: 2,
        electricResist: 2,
        explosionResist: 2,
        weight: 300,
        excludes: [],
        type: 'normal',
        width:'118px',
        top:'14px',
        left:'-20px'
    },
]
//Legs
var legs = [
    {
        name: 'Nothing',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        weight: 0,
        excludes: [],
        type: 'normal',
        robotTop:'55px',
        robotMiscTop:'201px',
        width:'100px',
        top:'148px',
        left:'-25px',
        leftLegTwo:'27px'
    },
    {
        name: 'GRAVE_DIGGERS',
        hp: 287,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 123,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
        robotTop:'0px',
        robotMiscTop:'264px',
        width:'100px',
        top:'148px',
        left:'-25px',
        leftLegTwo:'27px'
    },
    {
        name: 'IRON_BOOTS',
        hp: 478,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 138,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
        robotTop:'0px',
        robotMiscTop:'264px',
        width:'100px',
        top:'148px',
        left:'-25px',
        leftLegTwo:'27px'
    },
    {
        name: 'ROLLING_BEASTS',
        hp: 451,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 134,
        walking: 3,
        jumping: 0,
        excludes: [],
        type: 'normal',
        robotTop:'55px',
        robotMiscTop:'201px',
        width:'170px',
        top:'140px',
        left:'-64px',
        leftLegTwo:'-18px'
    },
    {
        name: 'THE_CLAW',
        hp: 860,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 150,
        walking: 0,
        jumping: 0,
        excludes: [],
        type: 'normal',
        robotTop:'34px',
        robotMiscTop:'230px',
        width:'190px',
        top:'144px',
        left:'-46px',
        leftLegTwo:'0px'
    },
    {
        name: 'SCORCHING_FEET',
        hp: 413,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 120,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
        robotTop:'0px',
        robotMiscTop:'264px',
        width:'100px',
        top:'148px',
        left:'-25px',
        leftLegTwo:'27px'
    },
    {
        name: 'DEVOURING_PAWS',
        hp: 394,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 121,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
        robotTop:'0px',
        robotMiscTop:'264px',
        width:'90px',
        top:'148px',
        left:'-25px',
        leftLegTwo:'27px'
    },
    {
        name: 'SPARKED_RUNNERS',
        hp: 363,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 114,
        walking: 3,
        jumping: 0,
        excludes: [],
        type: 'normal',
        robotTop:'55px',
        robotMiscTop:'201px',
        width:'170px',
        top:'140px',
        left:'-64px',
        leftLegTwo:'-18px'
    },
    {
        name: 'DYNAMIC_STOMPERS',
        hp: 372,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 118,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
        robotTop:'0px',
        robotMiscTop:'264px',
        width:'100px',
        top:'148px',
        left:'-25px',
        leftLegTwo:'27px'
    },
    {
        name: 'CHARGED_WALKERS',
        hp: 413,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 122,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
        robotTop:'0px',
        robotMiscTop:'264px',
        width:'100px',
        top:'148px',
        left:'-25px',
        leftLegTwo:'27px'
    },
    {
        name: 'LIGHTNING_SUPPORTERS',
        hp: 413,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 124,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
        robotTop:'0px',
        robotMiscTop:'264px',
        width:'100px',
        top:'148px',
        left:'-25px',
        leftLegTwo:'27px'
    },
    {
        name: 'DYNAMITE_BOOTS',
        hp: 413,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 136,
        walking: 1,
        jumping: 2,
        excludes: [],
        type: 'normal',
        robotTop:'0px',
        robotMiscTop:'264px',
        width:'96px',
        top:'148px',
        left:'-15px',
        leftLegTwo:'40px'
    },
    //fan items
    {
        name: 'ELEPHANT_FEET',
        hp: 613,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 126,
        walking: 1,
        jumping: 1,
        excludes: [],
        type: 'normal',
        robotTop:'0px',
        robotMiscTop:'264px',
        width:'110px',
        top:'148px',
        left:'-25px',
        leftLegTwo:'27px'
    },
    {
        name: 'Heat_Rollers',
        hp: 343,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 100,
        walking: 3,
        jumping: 0,
        excludes: [],
        type: 'normal',
        robotTop:'80px',
        robotMiscTop:'182px',
        width:'186px',
        top:'140px',
        left:'-64px',
        leftLegTwo:'-18px'
    },
    {
        name: 'TILTING_TOWER',
        hp: 342,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 102,
        walking: 1,
        jumping: 3,
        excludes: [],
        type: 'normal',
        robotTop:'0px',
        robotMiscTop:'264px',
        width:'110px',
        top:'148px',
        left:'-20px',
        leftLegTwo:'25px'
    },
]
// Drones
var drones = [
    {
        name: 'Nothing',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        weight: 0,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'ANGUISH',
        weight: 30,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'CLASH',
        weight: 43,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'DUSTMAKER',
        weight: 29,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'FACE_SHOCKER',
        weight: 41,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'HEAT_POINT',
        weight: 51,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'GREEDY',
        weight: 20,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'HURLBAT',
        weight: 28,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'MURMUR',
        weight: 43,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'NEMO',
        weight: 43,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'SHOCKWAVE',
        weight: 57,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'SNACK',
        weight: 30,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'SWOOP',
        weight: 22,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'TORMENT',
        weight: 29,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'VOID',
        weight: 29,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'WINDFORGE',
        weight: 27,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'FLAMEWAVE',
        weight: 53,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'BACKSTABBER',
        weight: 56,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'ELECTROLYTE',
        weight: 56,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'FIRE_FLY',
        weight: 56,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'TONTO',
        weight: 56,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'RAIL_GUN',
        weight: 56,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'SOLAR_TORCH',
        weight: 56,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'HEAT_GUN',
        weight: 56,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'HEAT_ROCKET',
        weight: 56,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'PHENOMEN',
        weight: 52,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'PYSHICAL_DESTROYER',
        weight: 56,
        excludes: [],
        type: 'normal',
    }
]
// Side weapons
var sideWeapons = [
    {
        name: 'Nothing',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        weight: 0,
        excludes: [],
        type: 'normal',
        side12Top:'127px',
        side13Left:'-10px',
        side34Top:'106px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'ABOMINATION_L',
        weight: 70,
        excludes: [],
        type: 'normal',
        attackType: 'rocket',
        minDamage: 212,
        maxDamage: 307,
        heatDamage: 71,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 12,
        psyResistDrain: 0,
        uses: 3,
        push: 1,
        heatCost: 44,
        energyCost: 19,
        damageIco: 'explosion',
        color: 'red',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'

    },
    {
        name: 'ANNIHILATION',
        weight: 65,
        excludes: [],
        type: 'normal',
        attackType: 'bullet',
        minDamage: 203,
        maxDamage: 341,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 15,
        uses: 3,
        push: 0,
        heatCost: 0,
        energyCost: 0,
        damageIco: 'psyhical',
        color: 'yellow',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'ARMOR_ANNIHILATOR_L',
        weight: 17,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage: 41,
        maxDamage: 44,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 40,
        uses: 1,
        push: 0,
        heatCost: 0,
        energyCost: 0,
        damageIco: 'psyhical',
        color: 'yellow',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'ARMOR_DISSOLVER_L',
        weight: 18,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage: 41,
        maxDamage: 55,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 2,
        push: 3,
        heatCost: 62,
        energyCost: 0,
        damageIco: 'psyhical',
        color: 'yellow',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'ASH_CREATOR_L',
        weight: 58,
        excludes: [],
        type: 'normal',
        attackType: 'flame',
        minDamage: 163,
        maxDamage: 213,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 180,
        totalEnergyDamage: 48,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 3,
        push: 0,
        heatCost: 31,
        energyCost: 93,
        damageIco: 'electric',
        color: 'blue',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'BACKBREAKER',
        weight: 44,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage: 228,
        maxDamage: 408,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 8,
        energyDamage: 180,
        totalEnergyDamage: 48,
        energyRegenDamage: 8,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 1,
        heatCost: 31,
        energyCost: 31,
        damageIco: 'psyhical',
        color: 'yellow',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'170px'
    },
    {
        name: 'BIGDADDY_L',
        weight: 53,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage: 203,
        maxDamage: 265,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 95,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 16,
        energyCost: 47,
        damageIco: 'electric',
        color: 'blue',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'85px'
    },
    {
        name: 'BLOODWEEP_L',
        weight: 34,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage: 147,
        maxDamage: 209,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 20,
        uses: 3,
        push: 0,
        heatCost: 31,
        energyCost: 31,
        damageIco: 'psyhical',
        color: 'yellow',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'85px'
    },
    {
        name: 'BRIGHTROAR_L',
        weight: 45,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage: 193,
        maxDamage: 311,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 103,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 9,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 13,
        energyCost: 50,
        damageIco: 'electric',
        color: 'blue',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'170px'
    },
    {
        name: 'BULLDOG_L',
        weight: 73,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage: 182,
        maxDamage: 406,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 67,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 10,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 3,
        push: 1,
        heatCost: 0,
        energyCost: 31,
        damageIco: 'electric',
        color: 'blue',
        side12Top:'80px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'BUNKER_SHELLL',
        weight: 50,
        excludes: [],
        type: 'normal',
        attackType: 'rocket',
        minDamage: 243,
        maxDamage: 463,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 123,
        totalEnergyDamage: 30,
        energyRegenDamage: 17,
        eleResDrain: 13,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 1,
        push: 1,
        heatCost: 0,
        energyCost: 31,
        damageIco: 'electric',
        color: 'blue',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'CHAOS_BRINGER_L',
        weight: 52,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage: 203,
        maxDamage: 265,
        heatDamage: 71,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 47,
        energyCost: 16,
        damageIco: 'explosion',
        color: 'red',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'85px'
    },
    {
        name: 'CORRUPT_LIGHT',
        weight: 51,
        excludes: [],
        type: 'normal',
        attackType: 'laser',
        minDamage: 140,
        maxDamage: 236,
        heatDamage: 93,
        totalHeatDamage: 24,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 47,
        energyCost: 16,
        damageIco: 'explosion',
        color: 'red',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'95px'
    },
    {
        name: 'CRIMSON_RAPTURE_L',
        weight: 58,
        excludes: [],
        type: 'normal',
        attackType: 'flame',
        minDamage: 163,
        maxDamage: 213,
        heatDamage: 135,
        totalHeatDamage: 48,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 3,
        push: 0,
        heatCost: 93,
        energyCost: 31,
        damageIco: 'explosion',
        color: 'red',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'DAWNBLAZE',
        weight: 52,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage: 203,
        maxDamage: 265,
        heatDamage: 71,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 5,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 47,
        energyCost: 16,
        damageIco: 'explosion',
        color: 'red',
        side12Top:'80px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'EMP',
        weight: 70,
        excludes: [],
        type: 'normal',
        attackType: 'bomb',
        minDamage: 37,
        maxDamage: 61,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 334,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 1,
        push: 0,
        heatCost: 0,
        energyCost: 393,
        damageIco: 'electric',
        color: 'blue',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'FLAMINATOR',
        weight: 47,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage: 148,
        maxDamage: 228,
        heatDamage: 93,
        totalHeatDamage: 24,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 0,
        energyCost: 110,
        damageIco: 'explosion',
        color: 'red',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'96px'
    },
    {
        name: 'Flaming_hammer',
        weight: 60,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage: 211,
        maxDamage: 354,
        heatDamage: 86,
        totalHeatDamage: 0,
        coolingDamage: 17,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 3,
        heatCost: 50,
        energyCost: 13,
        damageIco: 'explosion',
        color: 'red',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'170px'
    },
    {
        name: 'HEAT_BOMB',
        weight: 50,
        excludes: [],
        type: 'normal',
        attackType: 'bomb',
        minDamage: 40,
        maxDamage: 59,
        heatDamage: 393,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 1,
        push: 0,
        heatCost: 393,
        energyCost: 0,
        damageIco: 'explosion',
        color: 'red',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'HERONMARK_L',
        weight: 43,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage: 193,
        maxDamage: 311,
        heatDamage: 78,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 9,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 50,
        energyCost: 13,
        damageIco: 'explosion',
        color: 'red',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'190px'
    },
    {
        name: 'HOT_FLASH',
        weight: 66,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage: 148,
        maxDamage: 228,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 123,
        totalEnergyDamage: 24,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 110,
        energyCost: 0,
        damageIco: 'electric',
        color: 'blue',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'96px'
    },
    {
        name: 'LAST_WORDS',
        weight: 63,
        excludes: [],
        type: 'normal',
        attackType: 'bigBulletFromTop',
        minDamage: 185,
        maxDamage: 285,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 95,
        totalEnergyDamage: 0,
        energyRegenDamage: 13,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 3,
        push: 1,
        heatCost: 16,
        energyCost: 47,
        damageIco: 'electric',
        color: 'blue',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'96px'
    },
    {
        name: 'MAGMA_BLAST_L',
        weight: 55,
        excludes: [],
        type: 'normal',
        attackType: 'rocket',
        minDamage: 243,
        maxDamage: 463,
        heatDamage: 93,
        totalHeatDamage: 30,
        coolingDamage: 17,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 13,
        psyResistDrain: 0,
        uses: 1,
        push: 1,
        heatCost: 31,
        energyCost: 0,
        damageIco: 'explosion',
        color: 'red',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'MALICE_BEAM',
        weight: 55,
        excludes: [],
        type: 'normal',
        attackType: 'laser',
        minDamage: 140,
        maxDamage: 236,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 123,
        totalEnergyDamage: 24,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 16,
        energyCost: 47,
        damageIco: 'electric',
        color: 'blue',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'95px'
    },
    {
        name: 'MERCY_L',
        weight: 84,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage: 197,
        maxDamage: 440,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 10,
        uses: 3,
        push: 1,
        heatCost: 0,
        energyCost: 0,
        damageIco: 'psyhical',
        color: 'yellow',
        side12Top:'80px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'MORTAL_BULLET_L',
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage: 163,
        maxDamage: 213,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 123,
        totalEnergyDamage: 12,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 0,
        energyCost: 31,
        damageIco: 'electric',
        color: 'blue',
        side12Top:'80px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'110px'
    },
    {
        name: 'NIGHTFALL',
        weight: 49,
        excludes: [],
        type: 'normal',
        attackType: 'bullet',
        minDamage: 248,
        maxDamage: 366,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 11,
        uses: 3,
        push: 0,
        heatCost: 31,
        energyCost: 31,
        damageIco: 'psyhical',
        color: 'yellow',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'PURIFIER_L',
        weight: 49,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage: 163,
        maxDamage: 213,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 0,
        energyCost: 0,
        damageIco: 'psyhical',
        color: 'yellow',
        side12Top:'80px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'115px'
    },
    {
        name: 'RECKONING_L',
        weight: 86,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage: 182,
        maxDamage: 406,
        heatDamage: 50,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 10,
        psyResistDrain: 0,
        uses: 3,
        push: 1,
        heatCost: 31,
        energyCost: 0,
        damageIco: 'explosion',
        color: 'red',
        side12Top:'80px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'SERAPHBLADE_L',
        weight: 49,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage: 234,
        maxDamage: 376,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 12,
        uses: 999,
        push: 0,
        heatCost: 50,
        energyCost: 13,
        damageIco: 'psyhical',
        color: 'yellow',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'170px'
    },
    {
        name: 'SORROW_L',
        weight: 66,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage: 163,
        maxDamage: 213,
        heatDamage: 93,
        totalHeatDamage: 12,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 31,
        energyCost: 0,
        damageIco: 'explosion',
        color: 'red',
        side12Top:'80px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'115px'
    },
    {
        name: 'STORMWEAVER_L',
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage: 244,
        maxDamage: 319,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 114,
        totalEnergyDamage: 32,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 1,
        heatCost: 13,
        energyCost: 50,
        damageIco: 'electric',
        color: 'blue',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'170px'
    },
    {
        name: 'SWEETIE_L',
        weight: 42,
        excludes: [],
        type: 'normal',
        attackType: 'shootgun',
        minDamage: 159,
        maxDamage: 256,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 48,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 10,
        uses: 3,
        push: 0,
        heatCost: 31,
        energyCost: 31,
        damageIco: 'psyhical',
        color: 'yellow',
     side12Top:'80px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'115px'
    },
    {
        name: 'TERROR_CRY',
        weight: 46,
        excludes: [],
        type: 'normal',
        attackType: 'bigBulletFromTop',
        minDamage: 214,
        maxDamage: 331,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 3,
        push: 1,
        heatCost: 25,
        energyCost: 25,
        damageIco: 'psyhical',
        color: 'yellow',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'96px'
    },
    {
        name: 'TERRORBLADE_L',
        weight: 52,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage: 244,
        maxDamage: 319,
        heatDamage: 86,
        totalHeatDamage: 32,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 12,
        uses: 999,
        push: 1,
        heatCost: 50,
        energyCost: 13,
        damageIco: 'explosion',
        color: 'red',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'170px'
    },
    {
        name: 'ULTRABRIGHT',
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage: 203,
        maxDamage: 265,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 95,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 5,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 16,
        energyCost: 47,
        damageIco: 'electric',
        color: 'blue',
        side12Top:'80px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'101px'
    },
    {
        name: 'WARHAMMER',
        weight: 58,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage: 237,
        maxDamage: 398,
        heatDamage: 0,
        totalHeatDamage: 15,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 15,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 3,
        heatCost: 31,
        energyCost: 31,
        damageIco: 'psyhical',
        color: 'yellow',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'170px'
    },
    {
        name: 'VIKING_HAMMER',
        weight: 63,
        excludes: [],
        type: 'normal',
        attackType: 'mele',
        minDamage: 211,
        maxDamage: 354,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 114,
        totalEnergyDamage: 0,
        energyRegenDamage: 17,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 12,
        uses: 999,
        push: 3,
        heatCost: 13,
        energyCost: 50,
        damageIco: 'electric',
        color: 'blue',
        side12Top:'72px',
        side13Left:'-10px',
        side34Top:'105px',
        side24Left:'34px',
        width:'170px'
    }
]
// hooks
var hooks = [
    {
        name: 'Nothing_Hook',
        weight: 0,
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'FLAMING_GRAPPLING_HOOK_L',
        weight: 16,
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'PLATINUM_GRAPPLING_HOOK_L',
        weight: 17,
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'SHOCKING_GRAPPLING_HOOK_L',
        weight: 11,
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
         excludes: [],
        type: 'normal',
    },
]
// charge
var charge = [
    {
        name: 'Nothing_Charge',
        weight: 0,
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'CHARGE_ENGINE',
        weight: 20,
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        excludes: [],
        type: 'normal',
    },
]
// teleport
var teleport = [
    {
        name: 'Nothing_Teleport',
        weight: 0, hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'ADVANCED_TELEPORTER',
        weight: 11,
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'DOUBLE_TELEPORT',
        weight: 26, hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        excludes: [],
        type: 'normal',
    },
]
// shield
var shield = [
    {
        name: 'Nothing_Shield',
        weight: 0,
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'Super_Shield',
        weight: 11,
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        walking: 0,
        jumping: 0,
        excludes: [],
        type: 'normal',
    },
]
// modules
var modules = [
    {
        name: 'Nothing',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 0,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'HEAT_ENGINE',
        hp: 0,
        heat: 89,
        cooling: 42,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 25,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'HEAT_STORAGE_UNIT_L',
        hp: 0,
        heat: 134,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 22,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'COOLING_MASS_BOOSTER',
        hp: 0,
        heat: 0,
        cooling: 63,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 15,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'ENERGY_ENGINE',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 89,
        engRegen: 42,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 25,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'ENERGY_STORAGE_UNIT_L',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 134,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 22,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'ENERGY_MASS_BOOSTER',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 63,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 15,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'PLATINUM_PLATING_L',
        hp: 315,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 40,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'Iron_Plating__Epic',
        hp: 145,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 0,
        weight: 40,
        excludes: [],
        type: 'normal',
    },
    {
        name: 'MAXIMUM_PROTECTOR_L',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 39,
        electricResist: 39,
        explosionResist: 39,
        weight: 51,
        type: 'general',
        excludes: ['general', 'psyhic', 'electric', 'hot'],
    },
    {
        name: 'Savior_Resistance',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 16,
        electricResist: 16,
        explosionResist: 16,
        weight: 51,
        type: 'general',
        excludes: ['general', 'psyhic', 'electric', 'hot'],
    },
    {
        name: 'MIGHTY_PROTECTOR_L',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 59,
        electricResist: 0,
        explosionResist: 0,
        weight: 28,
        type: 'psyhic',
        excludes: ['general', 'psyhic'],
    },
    {
        name: 'Physical_Protector',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 24,
        electricResist: 0,
        explosionResist: 0,
        weight: 28,
        type: 'psyhic',
        excludes: ['general', 'psyhic'],
    },
    {
        name: 'SUPERCHARGE_PROTECTOR_L',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 59,
        explosionResist: 0,
        weight: 28,
        type: 'electric',
        excludes: ['general', 'electric'],
    },
    {
        name: 'Energy_Protector',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 24,
        explosionResist: 0,
        weight: 28,
        type: 'electric',
        excludes: ['general', 'electric'],
    },
    {
        name: 'ULTRAHOT_PROTECTOR_L',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 59,
        weight: 28,
        type: 'hot',
        excludes: ['general', 'hot'],
    },
    {
        name: 'Heat_Protector',
        hp: 0,
        heat: 0,
        cooling: 0,
        energy: 0,
        engRegen: 0,
        psyResist: 0,
        electricResist: 0,
        explosionResist: 24,
        weight: 28,
        type: 'hot',
        excludes: ['general', 'hot'],
    },
]
// Top weapons
var topWeapons = [
    {
        name: 'Nothing',
        weight: 0,
        excludes: [],
        type: 'normal',
        attackType: '',
        weight: 0,
        excludes: [],
        minDamage: 0,
        maxDamage: 0,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 0,
        push: 0,
        heatCost: 0,
        energyCost: 0,
        damageIco: '',
        color: '',
    },
    {
        name: 'BURNING_SHOWER',
        weight: 80,
        excludes: [],
        type: 'normal',
        attackType: 'multipleRockets',
        weight: 56,
        excludes: [],
        minDamage: 173,
        maxDamage: 345,
        heatDamage: 86,
        totalHeatDamage: 0,
        coolingDamage: 10,
        energyDamage: 95,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 12,
        psyResistDrain: 0,
        uses: 3,
        push: -2,
        heatCost: 81,
        energyCost: 0,
        damageIco: 'explosion',
        color: 'red',
        div1TopLeft:'-21px',
        div2TopLeft:'15px',
        div12Top:'18px',
        width:'90px'
    },
    {
        name:'DELERIUM_L',
        weight: 56,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        weight: 56,
        excludes: [],
        minDamage: 203,
        maxDamage: 265,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 95,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 5,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 16,
        energyCost: 47,
        damageIco: 'electric',
        color: 'blue',
        div1TopLeft:'-21px',
        div2TopLeft:'15px',
        div12Top:'18px',
        width:'100px'
    },
    {
        name:'DESERT_FURY_L',
        weight: 29,
        excludes: [],
        type: 'normal',
        attackType: 'sniper',
        weight: 56,
        excludes: [],
        minDamage: 154,
        maxDamage: 224,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 23,
        uses: 2,
        push: 0,
        heatCost: 16,
        energyCost: 16,
        damageIco: 'psyhical',
        color: 'yellow',
        div1TopLeft:'-6px',
        div2TopLeft:'34px',
        div12Top:'44px',
        width:'90px'
    },
    {
        name:'DESERT_SNAKE_L',
        weight: 63,
        excludes: [],
        type: 'normal',
        attackType: 'topBomb',
        weight: 56,
        excludes: [],
        minDamage: 192,
        maxDamage: 329,
        heatDamage: 71,
        totalHeatDamage: 0,
        coolingDamage: 7,
        energyDamage: 95,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: -1,
        heatCost: 75,
        energyCost: 25,
        damageIco: 'explosion',
        color: 'red',
        div1TopLeft:'-17px',
        div2TopLeft:'17px',
        div12Top:'44px',
        width:'120px'
    },
    {
        name:'DESOLATION',
        weight: 66,
        excludes: [],
        type: 'normal',
        attackType: 'rocketUp',
        weight: 56,
        excludes: [],
        minDamage: 210,
        maxDamage: 310,
        heatDamage: 71,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 10,
        psyResistDrain: 0,
        uses: 3,
        push: -1,
        heatCost: 81,
        energyCost: 0,
        damageIco: 'explosion',
        color: 'red',
        div1TopLeft:'-11px',
        div2TopLeft:'26px',
        div12Top:'15px',
        width:'56px'
    },
    {
        name:'FLAMING_SCOPE_L',
        weight: 21,
        excludes: [],
        type: 'normal',
        attackType: 'sniper',
        weight: 56,
        excludes: [],
        minDamage: 568,
        maxDamage: 741,
        heatDamage: 212,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 15,
        psyResistDrain: 0,
        uses: 1,
        push: 0,
        heatCost: 155,
        energyCost: 31,
        damageIco: 'explosion',
        color: 'red',
        div1TopLeft:'-18px',
        div2TopLeft:'26px',
        div12Top:'37px',
        width:'125px'
    },
    {
        name:'FALCON',
        weight: 19,
        excludes: [],
        type: 'normal',
        attackType: 'sniper',
        minDamage: 596,
        maxDamage: 997,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 1,
        push: 0,
        heatCost: 22,
        energyCost: 22,
        damageIco: 'psyhical',
        color: 'yellow',
         div1TopLeft:'-18px',
        div2TopLeft:'26px',
        div12Top:'37px',
        width:'125px'
    },
    {
        name:'GRIM_COBRA',
        weight: 63,
        excludes: [],
        type: 'normal',
        attackType: 'bigBulletFromTop',
        minDamage: 181,
        maxDamage: 290,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 95,
        totalEnergyDamage: 0,
        energyRegenDamage: 13,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 3,
        push: -1,
        heatCost: 16,
        energyCost: 47,
        damageIco: 'electric',
        color: 'blue',
        div1TopLeft:'-3px',
        div2TopLeft:'35px',
        div12Top:'35px',
        width:'80px'
    },
    {
        name:'HYSTERIA',
        weight: 55,
        excludes: [],
        type: 'normal',
        attackType: 'laser',
        minDamage: 150,
        maxDamage: 228,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 123,
        totalEnergyDamage: 24,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 16,
        energyCost: 47,
        damageIco: 'electric',
        color: 'blue',
        div1TopLeft:'-18px',
        div2TopLeft:'26px',
        div12Top:'37px',
        width:'125px'
    },
    {
        name:'LIGHTNING_SCOPE',
        weight: 23,
        excludes: [],
        type: 'normal',
        attackType: 'sniper',
        minDamage: 568,
        maxDamage: 741,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 283,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 15,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 1,
        push: 0,
        heatCost: 31,
        energyCost: 155,
        damageIco: 'electric',
        color: 'blue',
        div1TopLeft:'-18px',
        div2TopLeft:'26px',
        div12Top:'37px',
        width:'125px'
    },
    {
        name:'IRON_FRENZY_L',
        weight: 52,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage: 203,
        maxDamage: 265,
        heatDamage: 71,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 5,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 47,
        energyCost: 16,
        damageIco: 'explosion',
        color: 'red',
        div1TopLeft:'-21px',
        div2TopLeft:'15px',
        div12Top:'18px',
        width:'100px'
    },
    {
        name:'MIGHTY_CANNON_L',
        weight: 55,
        excludes: [],
        type: 'normal',
        attackType: 'topBomb',
        minDamage: 226,
        maxDamage: 387,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: -1,
        heatCost: 38,
        energyCost: 38,
        damageIco: 'psyhical',
        color: 'yellow',
        div1TopLeft:'-17px',
        div2TopLeft:'17px',
        div12Top:'44px',
        width:'120px'
        

    },
    {
        name:'NIGHT_EAGLE',
        weight: 46,
        excludes: [],
        type: 'normal',
        attackType: 'bigBulletFromTop',
        minDamage: 209,
        maxDamage: 336,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 3,
        push: -1,
        heatCost: 25,
        energyCost: 25,
        damageIco: 'psyhical',
        color: 'yellow',
        div1TopLeft:'-3px',
        div2TopLeft:'35px',
        div12Top:'35px',
        width:'80px'
    },
    {
        name:'RECKLESS_BEAM',
        weight: 35,
        excludes: [],
        type: 'normal',
        attackType: 'laser',
        minDamage: 188,
        maxDamage: 283,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 31,
        energyCost: 31,
        damageIco: 'psyhical',
        color: 'yellow',
        div1TopLeft:'-18px',
        div2TopLeft:'26px',
        div12Top:'37px',
        width:'125px'
    },
    {
        name:'SAVAGERY',
        weight: 51,
        excludes: [],
        type: 'normal',
        attackType: 'laser',
        minDamage: 150,
        maxDamage: 228,
        heatDamage: 93,
        totalHeatDamage: 24,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: 0,
        heatCost: 47,
        energyCost: 16,
        damageIco: 'explosion',
        color: 'red',
        div1TopLeft:'-18px',
        div2TopLeft:'26px',
        div12Top:'37px',
        width:'125px'
    },
    {
        name:'SPARTAN_CARNAGEL',
        weight: 51,
        excludes: [],
        type: 'normal',
        attackType: 'bullet',
        minDamage: 226,
        maxDamage: 387,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 15,
        uses: 3,
        push: 0,
        heatCost: 31,
        energyCost: 31,
        damageIco: 'psyhical',
        color: 'yellow',
        div1TopLeft:'-6px',
        div2TopLeft:'34px',
        div12Top:'40px',
        width:'98px'
    },
    {
        name:'SPINEFALL_L',
        weight: 67,
        excludes: [],
        type: 'normal',
        attackType: 'topBomb',
        minDamage: 192,
        maxDamage: 329,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 95,
        totalEnergyDamage: 0,
        energyRegenDamage: 7,
        eleResDrain: 0,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 999,
        push: -1,
        heatCost: 25,
        energyCost: 75,
        damageIco: 'electric',
        color: 'blue',
        div1TopLeft:'-17px',
        div2TopLeft:'17px',
        div12Top:'44px',
        width:'120px'
    },
    {
        name:'SUPREME_CANNON',
        weight: 66,
        excludes: [],
        type: 'normal',
        attackType: 'multipleRockets',
        minDamage: 205,
        maxDamage: 315,
        heatDamage: 71,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 12,
        psyResistDrain: 0,
        uses: 3,
        push: 1,
        heatCost: 44,
        energyCost: 19,
        damageIco: 'explosion',
        color: 'red',
        div1TopLeft:'-12px',
        div2TopLeft:'27px',
        div12Top:'20px',
        width:'78px'
    },
    {
        name:'VALIANT_SNIPER_L',
        weight: 51,
        excludes: [],
        type: 'normal',
        attackType: 'sniper',
        minDamage: 135,
        maxDamage: 196,
        heatDamage: 0,
        totalHeatDamage: 0,
        coolingDamage: 0,
        energyDamage: 189,
        totalEnergyDamage: 0,
        energyRegenDamage: 13,
        eleResDrain: 17,
        explosionResDrain: 0,
        psyResistDrain: 0,
        uses: 2,
        push: 0,
        heatCost: 0,
        energyCost: 31,
        damageIco: 'electric',
        color: 'blue',
        div1TopLeft:'-6px',
        div2TopLeft:'34px',
        div12Top:'44px',
        width:'90px'
    },
    {
        name:'VANDAL_RAGE',
        weight: 41,
        excludes: [],
        type: 'normal',
        attackType: 'laserBullet',
        minDamage: 143,
        maxDamage: 187,
        heatDamage: 44,
        totalHeatDamage: 0,
        coolingDamage: 46,
        energyDamage: 0,
        totalEnergyDamage: 0,
        energyRegenDamage: 0,
        eleResDrain: 0,
        explosionResDrain: 20,
        psyResistDrain: 0,
        uses: 1,
        push: 1,
        heatCost: 25,
        energyCost: 0,
        damageIco: 'explosion',
        color: 'red',
        div1TopLeft:'-18px',
        div2TopLeft:'26px',
        div12Top:'37px',
        width:'125px'
    },
]
